# ARC CHALLENGE PLAYGROUND AND TESTING AREA

In [21]:
import os
import json
import numpy as np

TRAINING_DATA_FOLDER_NAME = 'arcdata/evaluation';
fileNames = os.listdir(TRAINING_DATA_FOLDER_NAME);

def evaluate_effectiveness_of_function():
    with open(f'{TRAINING_DATA_FOLDER_NAME}/{fileNames[0]}', 'r') as file:
        data = json.loads(file.read())
        for i in data['train']:
            print('In out', i)
        for i in data['test']:
            print('In out', i)
evaluate_effectiveness_of_function()


In out {'input': [[8, 6], [6, 4]], 'output': [[8, 6, 8, 6, 8, 6], [6, 4, 6, 4, 6, 4], [6, 8, 6, 8, 6, 8], [4, 6, 4, 6, 4, 6], [8, 6, 8, 6, 8, 6], [6, 4, 6, 4, 6, 4]]}
In out {'input': [[7, 9], [4, 3]], 'output': [[7, 9, 7, 9, 7, 9], [4, 3, 4, 3, 4, 3], [9, 7, 9, 7, 9, 7], [3, 4, 3, 4, 3, 4], [7, 9, 7, 9, 7, 9], [4, 3, 4, 3, 4, 3]]}
In out {'input': [[3, 2], [7, 8]], 'output': [[3, 2, 3, 2, 3, 2], [7, 8, 7, 8, 7, 8], [2, 3, 2, 3, 2, 3], [8, 7, 8, 7, 8, 7], [3, 2, 3, 2, 3, 2], [7, 8, 7, 8, 7, 8]]}


In [22]:
import numpy as np
"""
Rotate a matrix (square or rectangle) clockwise
with two tests
"""
def rotate_clockwise(matrix):
    return np.array(list(zip(*(reversed(matrix)))))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_clockwise(matrix_square))
print(rotate_clockwise(matrix_rectangle))

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
[[5 1]
 [6 2]
 [7 3]
 [8 4]]


In [23]:
import numpy as np
"""
Rotate a matrix (square or rectangle) anticlockwise
with two tests
"""
def rotate_anticlockwise(matrix):
    return np.array(list(zip(*matrix))[::-1])

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_anticlockwise(matrix_square))
print(rotate_anticlockwise(matrix_rectangle))

[[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
[[4 8]
 [3 7]
 [2 6]
 [1 5]]


In [24]:
import numpy as np
"""
reverse a matrix (square or rectangle)
with two tests
"""
def reverse(matrix):
    return np.array(list(reversed(matrix)))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(reverse(matrix_square))
print(reverse(matrix_rectangle))

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[5 6 7 8]
 [1 2 3 4]]


In [25]:
import numpy as np

def add_border(matrix):
    return np.pad(matrix,1,mode='constant',constant_values=10)

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]

m1 = add_border(matrix_square)
m2 = add_border(matrix_rectangle)
print(m1)
print(m2)

[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10  9 10 11 12 10]
 [10 13 14 15 16 10]
 [10 10 10 10 10 10]]
[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10 10 10 10 10 10]]


In [15]:
import numpy as np
from functools import reduce # Python3
class Pixel:
    def __init__(self, color, coord):
        self.color = color
        self.coord = coord
matrix_square = np.array([[0,0,0,0,0,0,0,0],
                [0,0,1,1,1,0,0,0],
                [0,0,1,1,1,0,0,0],
                [0,0,0,0,0,0,0,0],
                [0,0,5,5,0,0,0,0],
                [0,0,0,0,0,1,1,0],
                [0,0,0,0,2,2,2,0],
                [0,0,0,0,0,0,0,0]])
def get_pixel_neighbours(matrix, pixel, seen_pos):
    if matrix[pixel[0], pixel[1]] == 0:
        return
    seen_pos.append(Pixel(matrix[pixel[0], pixel[1]], [pixel[0], pixel[1]]))
    for i in range(3):
        for j in range(3):
            d = Pixel(matrix[pixel[0]-1+i, pixel[1]-1+j], [pixel[0]-1+i, pixel[1]-1+j])
            #print(seen_pos, d.coord)
            if (all(obj.coord != d.coord for obj in seen_pos)) and d.color != 0:
                get_pixel_neighbours(matrix, d.coord, seen_pos)
    return seen_pos

#1. Suche erste Zahl, welche nicht 0 oder 10 ist
#2. Get Neighbours rekursiv bis alle neighbours schon im objekt oder 0 oder 10 sind
#3. suche nächste Zahl, welche in keinem objekt vorkommt und nicht 0 ist
def find_objects(matrix):
    cluster = []
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            print(cluster.flatten())
            if matrix[i][j] == 0 or (any([i,j] == obj.coord for obj in np.asarray(cluster).flatten())):
                print('here')
                continue
            print('there')
            d = get_pixel_neighbours(matrix, [i, j], [])
            print(d)
            np.append(cluster, d)
            print(cluster)
    return cluster

#print(get_pixel_neighbours(matrix_square, [1,2], []))
print(len(find_objects(matrix_square)))


[]
here
[]
here
[]
here
[]
here
[]
here
[]
here
[]
here
[]
here
[]
here
[]
here
[]
there
[<__main__.Pixel object at 0x00000201B5B98940>, <__main__.Pixel object at 0x00000201B68897F0>, <__main__.Pixel object at 0x00000201B6889B50>, <__main__.Pixel object at 0x00000201B5917CA0>, <__main__.Pixel object at 0x00000201B68D3C70>, <__main__.Pixel object at 0x00000201B68D3C40>]
[]
[]
there
[<__main__.Pixel object at 0x00000201B65DB130>, <__main__.Pixel object at 0x00000201B6889CA0>, <__main__.Pixel object at 0x00000201B5917220>, <__main__.Pixel object at 0x00000201B68D3BB0>, <__main__.Pixel object at 0x00000201B68D3A60>, <__main__.Pixel object at 0x00000201B68D39D0>]
[]
[]
there
[<__main__.Pixel object at 0x00000201B65DB160>, <__main__.Pixel object at 0x00000201B5B3B550>, <__main__.Pixel object at 0x00000201B6889B50>, <__main__.Pixel object at 0x00000201B68D3C70>, <__main__.Pixel object at 0x00000201B68D3BE0>, <__main__.Pixel object at 0x00000201B68D3A90>]
[]
[]
here
[]
here
[]
here
[]
here
[]
