# ARC CHALLENGE PLAYGROUND AND TESTING AREA

In [19]:
import os
import json
import numpy as np
"""
The idea of this function is that a newly created library function can be tested directly on the evaluation data 
(how many problems could be solved right away with this functionality).
"""
TRAINING_DATA_FOLDER_NAME = 'arcdata/evaluation';
fileNames = os.listdir(TRAINING_DATA_FOLDER_NAME);
fileNames = list(filter(lambda x: 'label' not in x, fileNames))

def evaluate_effectiveness_of_function(function):
    solved_files = []
    #print(fileNames)
    for fileName in fileNames:
        with open(f'{TRAINING_DATA_FOLDER_NAME}/{fileName}', 'r') as file:
            data = json.loads(file.read())
            result = []
            #print(data)
            for i in data['train']:
                #print(i)
                result.append(np.array_equal(function(i['input']), np.array(i['output'])))
            if np.all(result):
                solved_files.append(fileName)
    return solved_files

In [33]:
"""
Rotate a matrix (square or rectangle) clockwise
with two tests
"""
def rotate_clockwise(matrix):
    return np.array(list(zip(*(reversed(matrix)))))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', rotate_clockwise(matrix_square))
print('Rectangular matrix rotated:', rotate_clockwise(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(rotate_clockwise))

Square matrix rotated: [[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
Rectangular matrix rotated: [[5 1]
 [6 2]
 [7 3]
 [8 4]]
Solved problems with this function in training dataset: []


In [32]:
"""
Rotate a matrix (square or rectangle) anticlockwise
with two tests
"""
def rotate_anticlockwise(matrix):
    return np.array(list(zip(*matrix))[::-1])

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', rotate_anticlockwise(matrix_square))
print('Rectangular matrix rotated:', rotate_anticlockwise(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(rotate_anticlockwise))

Square matrix rotated: [[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
Rectangular matrix rotated: [[4 8]
 [3 7]
 [2 6]
 [1 5]]
Solved problems with this function in training dataset: []


In [31]:
"""
rotate matrix 180 degrees (square or rectangle)
with two tests
"""
def rotate_180(matrix):
    return rotate_clockwise(rotate_clockwise(matrix))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', rotate_180(matrix_square))
print('Rectangular matrix rotated:', rotate_180(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(rotate_180))

Square matrix rotated: [[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Rectangular matrix rotated: [[8 7 6 5]
 [4 3 2 1]]
Solved problems with this function in training dataset: []


In [30]:
"""
flip matrix horizontally (square or rectangle)
with two tests
"""
def flip_horizontally(matrix):
    return np.array(list(reversed(matrix)))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', flip_horizontally(matrix_square))
print('Rectangular matrix rotated:', flip_horizontally(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(flip_horizontally))

Square matrix rotated: [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Rectangular matrix rotated: [[5 6 7 8]
 [1 2 3 4]]
Solved problems with this function in training dataset: []


In [29]:
"""
flip matrix horizontally (square or rectangle)
with two tests
"""
def flip_vertically(matrix):
    return rotate_anticlockwise(flip_horizontally(rotate_clockwise(matrix)))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', flip_vertically(matrix_square))
print('Rectangular matrix rotated:', flip_vertically(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(flip_vertically))

Square matrix rotated: [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
Rectangular matrix rotated: [[4 3 2 1]
 [8 7 6 5]]
Solved problems with this function in training dataset: []
