# ARC CHALLENGE PLAYGROUND AND TESTING AREA

In [1]:
import os
import json
import numpy as np
"""
The idea of this function is that a newly created library function can be tested directly on the evaluation data 
(how many problems could be solved right away with this functionality).
"""
TRAINING_DATA_FOLDER_NAME = 'arcdata/evaluation';
fileNames = os.listdir(TRAINING_DATA_FOLDER_NAME);
fileNames = list(filter(lambda x: 'label' not in x, fileNames))

def evaluate_effectiveness_of_function(function):
    solved_files = []
    #print(fileNames)
    for fileName in fileNames:
        with open(f'{TRAINING_DATA_FOLDER_NAME}/{fileName}', 'r') as file:
            data = json.loads(file.read())
            result = []
            #print(data)
            for i in data['train']:
                #print(i)
                result.append(np.array_equal(function(i['input']), np.array(i['output'])))
            if np.all(result):
                solved_files.append(fileName)
    return solved_files

In [2]:
"""
Rotate a matrix (square or rectangle) clockwise
with two tests
"""
def rotate_clockwise(matrix):
    return np.array(list(zip(*(reversed(matrix)))))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', rotate_clockwise(matrix_square))
print('Rectangular matrix rotated:', rotate_clockwise(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(rotate_clockwise))

Square matrix rotated: [[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
Rectangular matrix rotated: [[5 1]
 [6 2]
 [7 3]
 [8 4]]
Solved problems with this function in training dataset: []


In [3]:
"""
Rotate a matrix (square or rectangle) anticlockwise
with two tests
"""
def rotate_anticlockwise(matrix):
    return np.array(list(zip(*matrix))[::-1])

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', rotate_anticlockwise(matrix_square))
print('Rectangular matrix rotated:', rotate_anticlockwise(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(rotate_anticlockwise))

Square matrix rotated: [[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
Rectangular matrix rotated: [[4 8]
 [3 7]
 [2 6]
 [1 5]]
Solved problems with this function in training dataset: []


In [4]:
"""
rotate matrix 180 degrees (square or rectangle)
with two tests
"""
def rotate_180(matrix):
    return rotate_clockwise(rotate_clockwise(matrix))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', rotate_180(matrix_square))
print('Rectangular matrix rotated:', rotate_180(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(rotate_180))

Square matrix rotated: [[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Rectangular matrix rotated: [[8 7 6 5]
 [4 3 2 1]]
Solved problems with this function in training dataset: []


In [5]:
"""
flip matrix horizontally (square or rectangle)
with two tests
"""
def flip_horizontally(matrix):
    return np.array(list(reversed(matrix)))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', flip_horizontally(matrix_square))
print('Rectangular matrix rotated:', flip_horizontally(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(flip_horizontally))

Square matrix rotated: [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Rectangular matrix rotated: [[5 6 7 8]
 [1 2 3 4]]
Solved problems with this function in training dataset: []


In [6]:
"""
flip matrix horizontally (square or rectangle)
with two tests
"""
def flip_vertically(matrix):
    return rotate_anticlockwise(flip_horizontally(rotate_clockwise(matrix)))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print('Square matrix rotated:', flip_vertically(matrix_square))
print('Rectangular matrix rotated:', flip_vertically(matrix_rectangle))
print('Solved problems with this function in training dataset:', evaluate_effectiveness_of_function(flip_vertically))

Square matrix rotated: [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
Rectangular matrix rotated: [[4 3 2 1]
 [8 7 6 5]]
Solved problems with this function in training dataset: []


In [7]:
import numpy as np

def add_border(matrix):
    return np.pad(matrix,1,mode='constant',constant_values=10)

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]

m1 = add_border(matrix_square)
m2 = add_border(matrix_rectangle)
print(m1)
print(m2)

[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10  9 10 11 12 10]
 [10 13 14 15 16 10]
 [10 10 10 10 10 10]]
[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10 10 10 10 10 10]]


In [8]:
import numpy as np

def equal_matrix_dimensions(matrix_one, matrix_two):
    """
    Checks if dimensions of input matrix and output matrix are equal
    :param array_one:
    :param array_two:
    :return: boolean
    """

    matrix_one_new = np.asarray(matrix_one)
    matrix_two_new = np.asarray(matrix_two)
    return matrix_one_new.shape == matrix_two_new.shape

matrix_one = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_two = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
matrix_three = [[1,2,3,4],[5,6,7,8]]

print(equal_matrix_dimensions(matrix_one, matrix_two))
print(equal_matrix_dimensions(matrix_one, matrix_three))

True
False


In [9]:
import numpy as np

def get_pixel_neighbours(matrix, pixel):
    neighbours = np.zeros((3,3))
    for i in range(3):
        for j in range(3):
            neighbours[i, j] = matrix[pixel[0]-1+i, pixel[1]-1+j]
    return neighbours

matrix_square = np.array([[1,2,3,4],
                          [5,6,7,8],
                          [9,10,11,12],
                          [13,14,15,16]])
matrix_rectangle = np.array([[1,2,3,4],
                             [5,6,7,8]])

print(get_pixel_neighbours(matrix_square,[0,1]))
print(get_pixel_neighbours(matrix_square,[2,1]))
print(get_pixel_neighbours(matrix_rectangle,[0,1]))

[[13. 14. 15.]
 [ 1.  2.  3.]
 [ 5.  6.  7.]]
[[ 5.  6.  7.]
 [ 9. 10. 11.]
 [13. 14. 15.]]
[[5. 6. 7.]
 [1. 2. 3.]
 [5. 6. 7.]]


In [10]:
import numpy as np
import collections

def check_same_color_sum(matrix_one, matrix_two):
    """
    Compares two matrices for equality of the number of the same color values in both.
    Matrices are converted to dictionaries for this purpose
    :param matrix_one:
    :param matrix_two:
    :return: added, removed, modified, same, equality
    """

    d1 = collections.Counter(np.asarray(matrix_one).flatten())
    d2 = collections.Counter(np.asarray(matrix_two).flatten())
    d1_keys = set(d1.keys())
    d2_keys = set(d2.keys())
    shared_keys = d1_keys.intersection(d2_keys)
    added = d1_keys - d2_keys
    removed = d2_keys - d1_keys
    modified = {o: (d1[o], d2[o]) for o in shared_keys if d1[o] != d2[o]}
    same = set(o for o in shared_keys if d1[o] == d2[o])
    equality = len(same) == len(d1)
    return added, removed, modified, same, equality


matrix_one = [[1, 2, 1], [2, 2, 2], [3, 1, 1]]
matrix_two = [[1, 2, 1], [2, 2, 2], [3, 2, 3]]
matrix_three = [[1, 2, 1, 2], [3, 2, 2, 1]]

added, removed, modified, same, equality = check_same_color_sum(matrix_one, matrix_two)

print("added: ", added)
print("remove: ", removed)
print("modified: ", modified)
print("same: ", same)
print("Equality: ", equality)
print()

added, removed, modified, same, equality = check_same_color_sum(matrix_one, matrix_three)

print("added: ", added)
print("remove: ", removed)
print("modified: ", modified)
print("same: ", same)
print("Equality: ", equality)

added:  set()
remove:  set()
modified:  {1: (4, 2), 2: (4, 5), 3: (1, 2)}
same:  set()
Equality:  False

added:  set()
remove:  set()
modified:  {1: (4, 3)}
same:  {2, 3}
Equality:  False


In [11]:
import numpy as np

def change_color_pixel(matrix, point, color):
    """
    changes color pixel (value in matrix)
    :param matrix:
    :param point:
    :param color: value from 1 to 9
    :return: matrix with changed pixel
    """
    matrix = np.asarray(matrix)
    print("before: \n", matrix)
    matrix[point] = color
    return matrix


matrix = np.array([[1, 2, 1], [2, 2, 2], [3, 1, 1]])
point = (1, 2)

matrix_changed = change_color_pixel(matrix, point, 9)
print("after: \n", matrix_changed)

before: 
 [[1 2 1]
 [2 2 2]
 [3 1 1]]
after: 
 [[1 2 1]
 [2 2 9]
 [3 1 1]]


In [12]:
import numpy as np

def move_pixel(matrix, pixel, vector):
    """
    Moves a pixel by the specified vector
    :param matrix:
    :param pixel:
    :param vector:
    :return: changed matrix
    """
    np_matrix = np.asarray(matrix)
    if (pixel[0] + vector[0] or pixel[1] + vector[1]) > np_matrix.shape[0] - 1:
        np_matrix[pixel] = 0
        return np_matrix
    color = np_matrix[pixel]
    np_matrix[pixel[0] + vector[0], pixel[1] + vector[1]] = color
    np_matrix[pixel] = 0
    return np_matrix

pixel = (0, 1)
vector = (1, 0)

matrix_one = [[0, 2, 0], [0, 0, 0], [0, 0, 0]]
print("matrix_one: \n", matrix_one)
print(move_pixel(matrix_one, pixel, vector))


matrix_two = [[0, 2, 0, 0] ,[0, 0, 0, 0]]
print("matrix_two: \n", matrix_two)
print(move_pixel(matrix_two, pixel, vector))



matrix_one: 
 [[0, 2, 0], [0, 0, 0], [0, 0, 0]]
[[0 0 0]
 [0 2 0]
 [0 0 0]]
matrix_two: 
 [[0, 2, 0, 0], [0, 0, 0, 0]]
[[0 0 0 0]
 [0 2 0 0]]


In [13]:
import numpy as np

def matrix_per_color(matrix):
    """
    Extract all equal color pixels from a matrix and return one matrix per color
    :param matrix:
    :return: result_matrices
    """
    result_matrices = []
    for i in np.unique(matrix):
        matrix_check_for_i = np.copy(matrix == i)
        result_matrix = matrix * matrix_check_for_i
        result_matrices.append(result_matrix)
    return result_matrices

matrix_one = [[1, 2, 1], [2, 2, 2], [3, 1, 1]]
matrix_two = [[1, 5, 2], [5, 2, 1], [2, 1, 6]]

results_one = matrix_per_color(matrix_one)
results_two = matrix_per_color(matrix_two)

print(results_one)
print()
print(results_two)

[array([[1, 0, 1],
       [0, 0, 0],
       [0, 1, 1]]), array([[0, 2, 0],
       [2, 2, 2],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 0, 0],
       [3, 0, 0]])]

[array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]]), array([[0, 0, 2],
       [0, 2, 0],
       [2, 0, 0]]), array([[0, 5, 0],
       [5, 0, 0],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 6]])]


In [14]:
def change_color_object(matrix_copied, colorobject, color):
    """
    changes color of a whole object in a matrix
    :param matrix:
    :param object:
    :param color:
    :return:
    """

    for pixel in colorobject:
        change_color_pixel(matrix_copied, pixel, color)
    return matrix_copied

matrix = np.array([[1, 2, 1], [2, 2, 2], [9, 9, 1]])
points = [(2, 0), (2, 1)]

matrix_changed = change_color_object(matrix, points, 4)

print(matrix_changed)

before: 
 [[1 2 1]
 [2 2 2]
 [9 9 1]]
before: 
 [[1 2 1]
 [2 2 2]
 [4 9 1]]
[[1 2 1]
 [2 2 2]
 [4 4 1]]


In [15]:
import numpy as np

def move_object(matrix, colorobject, vector):
    """
    Moves an object by the specified vector
    :param matrix:
    :param colorobject:
    :param vector:
    :return: changed matrix
    """
    np_matrix = np.asarray(matrix)
    print(np_matrix)
    for pixel in colorobject:
        move_pixel(np_matrix, pixel, vector)
    return np_matrix


matrix = [[0, 1, 0, 0, 0], [1, 1, 1, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
colorobject = [(0, 1), (1, 0), (1, 1), (1, 2), (2, 1)]
vector = (2, 2)

print(move_object(matrix, colorobject, vector))

[[0 1 0 0 0]
 [1 1 1 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 1 1]
 [0 0 0 1 0]]


In [16]:
import numpy as np


def gravitate_pixel(matrix, pixel):
    """
    Pixel following the gravitational force to the lowest possible field in the matrix
    :param matrix:
    :param pixel: which should be moved
    :return: matrix_changed
    """

    point = (pixel[1], pixel[0])
    row = point[0]
    column = point[1]
    matrix_changed = np.asarray(matrix)
    print("before: \n", matrix_changed)
    color = matrix_changed[row][column]
    matrix_changed[row][column] = 0
    shape = matrix_changed.shape[0]
    for i in range(row+1, shape):
        if matrix[i][column] == 0:
            continue
        if matrix[i][column] != 0:
            point_new = (i-1, column)
            matrix_changed[point_new[0]][point_new[1]] = color
        else:
            point_new = (i, column)
            matrix_changed[point_new[0]][point_new[1]] = color
    return matrix_changed #add matrix.tolist() when convert to input type of matrix


matrix = [[0,0,2,0],[0,2,0,0],[0,0,0,0],[1,1,1,1]]

pixel = [2, 0]

print("after: \n", gravitate_pixel(matrix,pixel))


before: 
 [[0 0 2 0]
 [0 2 0 0]
 [0 0 0 0]
 [1 1 1 1]]
after: 
 [[0 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [1 1 1 1]]


In [17]:
import numpy as np

def gravitate_object(matrix, pixel_group):
    """
    Group of Pixels (as object) following the gravitational force to the lowest possible fields in the matrix
    :param matrix:
    :param object: group of pixels which should be moved
    :return: matrix_changed
    """
    #print("before:\n", np.asarray(matrix))
    for pixel in pixel_group:
        matrix = gravitate_pixel(matrix, pixel)
    return matrix


matrix = [[0, 0, 2, 0], [0, 2, 0, 0], [0, 0, 0, 0], [1, 1, 1, 1]]

pixel_group = [[2, 0], [1, 1]]

print("after\n", gravitate_object(matrix, pixel_group))

before: 
 [[0 0 2 0]
 [0 2 0 0]
 [0 0 0 0]
 [1 1 1 1]]
before: 
 [[0 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [1 1 1 1]]
after
 [[0 0 0 0]
 [0 0 0 0]
 [0 2 2 0]
 [1 1 1 1]]


In [18]:
import numpy as np


def connect_diagonal(matrix, pixel_src, pixel_dest):
    """
    Diagonal connection of two points. Diagonal gets the color of the start pixel. 
    :param matrix:
    :param pixel_src
    :param pixel_dest
    :return: matrix_changed
    """
    print("before\n", np.asarray(matrix))
    point_src = (pixel_src[1],pixel_src[0])
    point_dest = (pixel_dest[1],pixel_dest[0])

    row_src = point_src[0]
    column_src = point_src[1]

    row_dest = point_dest[0]
    #column_dest = point_dest[1]
    color = matrix[row_src][column_src]
#bottom-top
    if row_src < row_dest:
        for i in range(row_src, row_dest-1):
            matrix[row_src + 1][column_src + 1] = color
            row_src += 1
            column_src += 1
#top-bottom
    else:
        for i in range(row_dest, row_src-1):
            matrix[row_src-1][column_src+1] = color
            row_src -=1
            column_src +=1
    return matrix


#bottom-top
matrix = [[0, 0, 0, 0, 1], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0]]

pixel_src = [0, 4]
pixel_dest = [4, 0]

print("after\n", np.asarray(connect_diagonal(matrix, pixel_src, pixel_dest)))

#top- bottom
matrix = [[0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 2]]

pixel_src = [1, 1]
pixel_dest = [4, 4]

print("after\n", np.asarray(connect_diagonal(matrix, pixel_src, pixel_dest)))


#top- bottom
matrix = [[0, 0, 0, 0, 1], [0, 0, 4, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 0, 3, 0, 2]]

pixel_src = [1, 3]
pixel_dest = [4, 0]

print("after\n", np.asarray(connect_diagonal(matrix, pixel_src, pixel_dest)))


before
 [[0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]]
after
 [[0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]
before
 [[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 2]]
after
 [[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 2]]
before
 [[0 0 0 0 1]
 [0 0 4 0 0]
 [0 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 2]]
after
 [[0 0 0 0 1]
 [0 0 4 2 0]
 [0 0 2 0 0]
 [0 2 0 0 0]
 [0 0 3 0 2]]


In [19]:
import numpy as np


def connect_horizontal_vertical(matrix, pixel_src, pixel_dest):
    """
    Connection of two pixels via horizontal - vertical connection. Pixel receives the color of the start pixel
    :param matrix:
    :param pixel_src:
    :param pixel_dest:
    :return: matrix_changed
    """
    point_src = (pixel_src[1],pixel_src[0])
    point_dest = (pixel_dest[1],pixel_dest[0])

    row_src = point_src[0]
    column_src = point_src[1]

    row_dest = point_dest[0]
    column_dest = point_dest[1]

    color = matrix[row_src][column_src]
    
    print("before\n", np.asarray(matrix))

    if row_src < row_dest:
        #top-bottom
        for i in range(column_src + 1, column_dest +1):
            matrix[row_src][column_src + 1] = color
            column_src +=1
        for j in range(row_src +1, row_dest):
            matrix[row_src+1][column_dest] = color
            row_src += 1
    else:
        #bottom-top
        for i in range(column_src + 1, column_dest + 1):
            matrix[row_src][column_src + 1] = color
            column_src += 1
        for j in range(row_dest +1, row_src):
            matrix[row_src - 1][column_dest] = color
            row_src -= 1
    return matrix



#bottom-top
matrix = [[0, 0, 0, 2, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

pixel_src = [0, 3]
pixel_dest = [3, 0]

print("after\n", np.asarray(connect_horizontal_vertical(matrix, pixel_src, pixel_dest)))

#top-bottom
matrix = [[0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 2]]

pixel_src = [1, 1]
pixel_dest = [4, 4]

print("after\n", np.asarray(connect_horizontal_vertical(matrix, pixel_src, pixel_dest)))


#bottom-top
matrix = [[0, 0, 0, 0, 2], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0]]

pixel_src = [0, 2]
pixel_dest = [4, 0]

print("after\n", np.asarray(connect_horizontal_vertical(matrix, pixel_src, pixel_dest)))

before
 [[0 0 0 2 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]]
after
 [[0 0 0 2 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [1 1 1 1 0]
 [0 0 0 0 0]]
before
 [[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 2]]
after
 [[0 0 0 0 0]
 [0 1 1 1 1]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 0 0 2]]
before
 [[0 0 0 0 2]
 [0 0 0 0 0]
 [1 0 0 0 0]]
after
 [[0 0 0 0 2]
 [0 0 0 0 1]
 [1 1 1 1 1]]


In [20]:
import numpy as np
BORDER_VALUE = -1
class Pixel:
    def __init__(self, color, coord):
        self.color = color
        self.coord = coord
        
class Grid:
    def __init__(self, raw_grid):
        self.raw = raw_grid
        self.shape = raw_grid.shape
        self.sum = np.sum(raw_grid)
        self.size = len(np.nonzero(raw_grid!=BORDER_VALUE))
        self.pixels = [Pixel(color, i) for i,color in enumerate(raw_grid.flatten())]
        self.colors = np.unique(raw_grid)
        self.objects = []
        self.patterns = []
        
pixel = Pixel(1, [1,2])
pixel2 = Pixel(1, [1,2])
grid = np.asarray([[1, 2, 1], [2, 2, 2], [3, 1, 1]])
g = Grid(grid)
print('Shape:', g.shape)
print('Sum:',g.sum)
print('Size:',g.size)
print('Pixels:', g.pixels)
print('Colors:', g.colors)
print('Objects:', g.objects)
print('Patterns:', g.patterns)


Shape: (3, 3)
Sum: 15
Size: 2
Pixels: [<__main__.Pixel object at 0x00000238A3DAAEB0>, <__main__.Pixel object at 0x00000238A3DAAF70>, <__main__.Pixel object at 0x00000238A3DAAFD0>, <__main__.Pixel object at 0x00000238A3DAAD30>, <__main__.Pixel object at 0x00000238A3DAACD0>, <__main__.Pixel object at 0x00000238A3DAAC70>, <__main__.Pixel object at 0x00000238A3DAAC10>, <__main__.Pixel object at 0x00000238A3DAAB80>, <__main__.Pixel object at 0x00000238A3DAAB20>]
Colors: [1 2 3]
Objects: []
Patterns: []


In [23]:
import numpy as np
x = np.asarray([[1,2,3,-1],[1,2,3,-1]])
len(np.nonzero(x!=-1)[0])


6

In [56]:
import numpy as np
import preprocessing as pp
from pprint import pprint
from functools import reduce # Python3

pp.BORDER_VALUE = 0
class Pixel:
    def getX(self):
        return self.coord[0]
    def getY(self):
        return self.coord[1]
    def __init__(self, color, coord):
        self.color = color
        self.coord = coord
        
class Grid:
    def getPixels(self):
        return self.pixels
    def __init__(self, raw_grid, pixels=[]):
        self.raw = raw_grid
        self.shape = raw_grid.shape
        self.sum = np.sum(raw_grid)
        self.size = len(np.nonzero(raw_grid!=0))
        if(pixels):
            self.pixels = pixels
        else:
            self.pixels = [Pixel(color, [i[0], i[1]]) for i, color in np.ndenumerate(raw_grid)]
        self.colors = np.unique(raw_grid)
        self.objects = find_objects(pp.add_border(raw_grid), np.asarray(raw_grid).size)
        
matrix_square = np.array([[0,0,0,0,0,0,0,0],
                [0,0,1,1,1,0,0,0],
                [0,0,1,1,1,0,0,0],
                [0,0,0,0,0,0,0,0],
                [0,0,5,5,0,0,0,0],
                [0,0,0,0,0,1,1,0],
                [0,0,0,0,2,2,2,0],
                [0,0,0,0,0,0,0,0]])

def get_pixel_neighbours(matrix, pixel, seen_pos):
    if matrix[pixel[0], pixel[1]] == 0:
        return
    seen_pos.append(Pixel(matrix[pixel[0], pixel[1]], [pixel[0], pixel[1]]))
    for i in range(3):
        for j in range(3):
            d = Pixel(matrix[pixel[0]-1+i, pixel[1]-1+j], [pixel[0]-1+i, pixel[1]-1+j])
            if (all(obj.coord != d.coord for obj in seen_pos)) and d.color != 0:
                get_pixel_neighbours(matrix, d.coord, seen_pos)
    return seen_pos

#1. Suche erste Zahl, welche nicht 0 oder 10 ist
#2. Get Neighbours rekursiv bis alle neighbours schon im objekt oder 0 oder 10 sind
#3. suche nächste Zahl, welche in keinem objekt vorkommt und nicht 0 ist
def find_objects(matrix, size):
    #print(matrix)
    cluster = []
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if matrix[i][j] == 0 or (cluster and any([i,j] == obj.coord for obj in np.concatenate(np.asarray(list(map(Grid.getPixels, cluster)), dtype=object)).ravel())):
                continue
            d = get_pixel_neighbours(matrix, [i, j], [])
            if math.ceil(np.asarray(d).size / 2) * 2 == size:
                return
            raw_child = normalize(d)
            cluster.append(Grid(raw_child, d))
    return cluster

def normalize(pixels):
    x = max(list(map(Pixel.getX, pixels))) - min(list(map(Pixel.getX, pixels)))
    y = max(list(map(Pixel.getY, pixels))) - min(list(map(Pixel.getY, pixels)))
    raw = np.zeros((x + 1,y + 1))
    
    for p in pixels:
        raw[(p.getX() - min(list(map(Pixel.getX, pixels))), p.getY() - min(list(map(Pixel.getY, pixels))))] = p.color
    return raw
    

pprint(Grid(matrix_square).size)

2


In [7]:
import preprocessing as pp
g = pp.Grid(np.array([[0,0,0,0,0,0,0,0],
                [0,0,1,1,1,0,0,0],
                [0,0,1,1,1,0,0,0],
                [0,0,0,0,0,0,0,0],
                [0,0,5,5,0,0,0,0],
                [0,0,0,0,0,1,1,0],
                [0,0,0,0,2,2,2,0],
                [0,0,0,0,0,0,0,0]]))
print(map(g.pixels, g))

No err until here: <preprocessing.Grid object at 0x00000206043B2F10>
No err until here: <preprocessing.Grid object at 0x00000206043B2F10>


TypeError: 'Grid' object is not iterable

In [2]:
obj = []
obj = 1
obj

1

In [58]:
test = [[1,2,3,4], [1,2,3,4]]
np.asarray(test).size

8

IndexError: tuple index out of range

In [2]:
import math
math.ceil(5 / 2) * 2

6

In [12]:
test = [[1,2,3,4],
        [5,6,7,8],[9,10,11,12]]
test

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [18]:
for i, x in np.ndenumerate(test):
    if i == (0,0):
        print('test')
    print(i, x)

test
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(2, 0) 9
(2, 1) 10
(2, 2) 11
(2, 3) 12


In [38]:
True ? 'a' : 'b'

SyntaxError: invalid syntax (1115586783.py, line 1)