# ARC CHALLENGE PLAYGROUND AND TESTING AREA

In [45]:
import os
import json
import numpy as np

TRAINING_DATA_FOLDER_NAME = 'arcdata/evaluation';
fileNames = os.listdir(TRAINING_DATA_FOLDER_NAME);

def evaluate_effectiveness_of_function():
    with open(f'{TRAINING_DATA_FOLDER_NAME}/{fileNames[0]}', 'r') as file:
        data = json.loads(file.read())
        for i in data['train']:
            print('In out', i)
        for i in data['test']:
            print('In out', i)
evaluate_effectiveness_of_function()


In out {'input': [[8, 6], [6, 4]], 'output': [[8, 6, 8, 6, 8, 6], [6, 4, 6, 4, 6, 4], [6, 8, 6, 8, 6, 8], [4, 6, 4, 6, 4, 6], [8, 6, 8, 6, 8, 6], [6, 4, 6, 4, 6, 4]]}
In out {'input': [[7, 9], [4, 3]], 'output': [[7, 9, 7, 9, 7, 9], [4, 3, 4, 3, 4, 3], [9, 7, 9, 7, 9, 7], [3, 4, 3, 4, 3, 4], [7, 9, 7, 9, 7, 9], [4, 3, 4, 3, 4, 3]]}
In out {'input': [[3, 2], [7, 8]], 'output': [[3, 2, 3, 2, 3, 2], [7, 8, 7, 8, 7, 8], [2, 3, 2, 3, 2, 3], [8, 7, 8, 7, 8, 7], [3, 2, 3, 2, 3, 2], [7, 8, 7, 8, 7, 8]]}


In [17]:
import numpy as np
"""
Rotate a matrix (square or rectangle) clockwise
with two tests
"""
def rotate_clockwise(matrix):
    return np.array(list(zip(*(reversed(matrix)))))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_clockwise(matrix_square))
print(rotate_clockwise(matrix_rectangle))

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
None
[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
[[5 1]
 [6 2]
 [7 3]
 [8 4]]


In [7]:
import numpy as np
"""
Rotate a matrix (square or rectangle) anticlockwise
with two tests
"""
def rotate_anticlockwise(matrix):
    return np.array(list(zip(*matrix))[::-1])

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_anticlockwise(matrix_square))
print(rotate_anticlockwise(matrix_rectangle))

[[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
[[4 8]
 [3 7]
 [2 6]
 [1 5]]


In [9]:
import numpy as np
"""
reverse a matrix (square or rectangle)
with two tests
"""
def reverse(matrix):
    return np.array(list(reversed(matrix)))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(reverse(matrix_square))
print(reverse(matrix_rectangle))

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[5 6 7 8]
 [1 2 3 4]]


In [ ]:
import numpy as np

def add_border(matrix):
    return np.pad(matrix,1,mode='constant',constant_values=10)

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]

m1 = add_border(matrix_square)
m2 = add_border(matrix_rectangle)
print(m1)
print(m2)

[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10  9 10 11 12 10]
 [10 13 14 15 16 10]
 [10 10 10 10 10 10]]
[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10 10 10 10 10 10]]


In [2]:
import numpy as np

def equal_matrix_dimensions(matrix_one, matrix_two):
    """
    Checks if dimensions of input matrix and output matrix are equal
    :param array_one:
    :param array_two:
    :return: boolean
    """

    matrix_one_new = np.asarray(matrix_one)
    matrix_two_new = np.asarray(matrix_two)
    return matrix_one_new.shape == matrix_two_new.shape

matrix_one = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_two = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
matrix_three = [[1,2,3,4],[5,6,7,8]]

print(equal_matrix_dimensions(matrix_one, matrix_two))
print(equal_matrix_dimensions(matrix_one, matrix_three))

True
False


In [1]:
import numpy as np

def get_pixel_neighbours(matrix, pixel):
    neighbours = np.zeros((3,3))
    for i in range(3):
        for j in range(3):
            neighbours[i, j] = matrix[pixel[0]-1+i, pixel[1]-1+j]
    return neighbours

matrix_square = np.array([[1,2,3,4],
                          [5,6,7,8],
                          [9,10,11,12],
                          [13,14,15,16]])
matrix_rectangle = np.array([[1,2,3,4],
                             [5,6,7,8]])

print(get_pixel_neighbours(matrix_square,[0,1]))
print(get_pixel_neighbours(matrix_square,[2,1]))
print(get_pixel_neighbours(matrix_rectangle,[0,1]))

[[13. 14. 15.]
 [ 1.  2.  3.]
 [ 5.  6.  7.]]
[[ 5.  6.  7.]
 [ 9. 10. 11.]
 [13. 14. 15.]]
[[5. 6. 7.]
 [1. 2. 3.]
 [5. 6. 7.]]


In [1]:
import numpy as np
import collections

def check_same_color_sum(matrix_one, matrix_two):
    """
    Compares two matrices for equality of the number of the same color values in both.
    Matrices are converted to dictionaries for this purpose
    :param matrix_one:
    :param matrix_two:
    :return: added, removed, modified, same, equality
    """

    d1 = collections.Counter(np.asarray(matrix_one).flatten())
    d2 = collections.Counter(np.asarray(matrix_two).flatten())
    d1_keys = set(d1.keys())
    d2_keys = set(d2.keys())
    shared_keys = d1_keys.intersection(d2_keys)
    added = d1_keys - d2_keys
    removed = d2_keys - d1_keys
    modified = {o: (d1[o], d2[o]) for o in shared_keys if d1[o] != d2[o]}
    same = set(o for o in shared_keys if d1[o] == d2[o])
    equality = len(same) == len(d1)
    return added, removed, modified, same, equality


matrix_one = [[1, 2, 1], [2, 2, 2], [3, 1, 1]]
matrix_two = [[1, 2, 1], [2, 2, 2], [3, 2, 3]]
matrix_three = [[1, 2, 1, 2], [3, 2, 2, 1]]

added, removed, modified, same, equality = check_same_color_sum(matrix_one, matrix_two)

print("added: ", added)
print("remove: ", removed)
print("modified: ", modified)
print("same: ", same)
print("Equality: ", equality)
print()

added, removed, modified, same, equality = check_same_color_sum(matrix_one, matrix_three)

print("added: ", added)
print("remove: ", removed)
print("modified: ", modified)
print("same: ", same)
print("Equality: ", equality)

added:  set()
remove:  set()
modified:  {1: (4, 2), 2: (4, 5), 3: (1, 2)}
same:  set()
Equality:  False

added:  set()
remove:  set()
modified:  {1: (4, 3)}
same:  {2, 3}
Equality:  False


In [2]:
import numpy as np

def change_color_pixel(matrix, point, color):
    """
    changes color pixel (value in matrix)
    :param matrix:
    :param point:
    :param color: value from 1 to 9
    :return: matrix with changed pixel
    """
    matrix = np.asarray(matrix)
    print("before: \n", matrix)
    matrix[point] = color
    return matrix


matrix = np.array([[1, 2, 1], [2, 2, 2], [3, 1, 1]])
point = (1, 2)

matrix_changed = change_color_pixel(matrix, point, 9)
print("after: \n", matrix_changed)

before: 
 [[1 2 1]
 [2 2 2]
 [3 1 1]]
after: 
 [[1 2 1]
 [2 2 9]
 [3 1 1]]


In [3]:
import numpy as np

def move_pixel(matrix, pixel, vector):
    """
    Moves a pixel by the specified vector
    :param matrix:
    :param pixel:
    :param vector:
    :return: changed matrix
    """
    np_matrix = np.asarray(matrix)
    if (pixel[0] + vector[0] or pixel[1] + vector[1]) > np_matrix.shape[0] - 1:
        np_matrix[pixel] = 0
        return np_matrix
    color = np_matrix[pixel]
    np_matrix[pixel[0] + vector[0], pixel[1] + vector[1]] = color
    np_matrix[pixel] = 0
    return np_matrix

pixel = (0, 1)
vector = (1, 0)

matrix_one = [[0, 2, 0], [0, 0, 0], [0, 0, 0]]
print("matrix_one: \n", matrix_one)
print(move_pixel(matrix_one, pixel, vector))


matrix_two = [[0, 2, 0, 0] ,[0, 0, 0, 0]]
print("matrix_two: \n", matrix_two)
print(move_pixel(matrix_two, pixel, vector))



matrix_one: 
 [[0, 2, 0], [0, 0, 0], [0, 0, 0]]
[[0 0 0]
 [0 2 0]
 [0 0 0]]
matrix_two: 
 [[0, 2, 0, 0], [0, 0, 0, 0]]
[[0 0 0 0]
 [0 2 0 0]]


In [4]:
import numpy as np

def matrix_per_color(matrix):
    """
    Extract all equal color pixels from a matrix and return one matrix per color
    :param matrix:
    :return: result_matrices
    """
    result_matrices = []
    for i in np.unique(matrix):
        matrix_check_for_i = np.copy(matrix == i)
        result_matrix = matrix * matrix_check_for_i
        result_matrices.append(result_matrix)
    return result_matrices

matrix_one = [[1, 2, 1], [2, 2, 2], [3, 1, 1]]
matrix_two = [[1, 5, 2], [5, 2, 1], [2, 1, 6]]

results_one = matrix_per_color(matrix_one)
results_two = matrix_per_color(matrix_two)

print(results_one)
print()
print(results_two)

[array([[1, 0, 1],
       [0, 0, 0],
       [0, 1, 1]]), array([[0, 2, 0],
       [2, 2, 2],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 0, 0],
       [3, 0, 0]])]

[array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]]), array([[0, 0, 2],
       [0, 2, 0],
       [2, 0, 0]]), array([[0, 5, 0],
       [5, 0, 0],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 6]])]


In [7]:
def change_color_object(matrix_copied, colorobject, color):
    """
    changes color of a whole object in a matrix
    :param matrix:
    :param object:
    :param color:
    :return:
    """

    for pixel in colorobject:
        change_color_pixel(matrix_copied, pixel, color)
    return matrix_copied

matrix = np.array([[1, 2, 1], [2, 2, 2], [9, 9, 1]])
points = [(2, 0), (2, 1)]

matrix_changed = change_color_object(matrix, points, 4)

print(matrix_changed)

before: 
 [[1 2 1]
 [2 2 2]
 [9 9 1]]
before: 
 [[1 2 1]
 [2 2 2]
 [4 9 1]]
[[1 2 1]
 [2 2 2]
 [4 4 1]]
