# ARC CHALLENGE PLAYGROUND AND TESTING AREA

In [45]:
import os
import json
import numpy as np

TRAINING_DATA_FOLDER_NAME = 'arcdata/evaluation';
fileNames = os.listdir(TRAINING_DATA_FOLDER_NAME);

def evaluate_effectiveness_of_function():
    with open(f'{TRAINING_DATA_FOLDER_NAME}/{fileNames[0]}', 'r') as file:
        data = json.loads(file.read())
        for i in data['train']:
            print('In out', i)
        for i in data['test']:
            print('In out', i)
evaluate_effectiveness_of_function()


In out {'input': [[8, 6], [6, 4]], 'output': [[8, 6, 8, 6, 8, 6], [6, 4, 6, 4, 6, 4], [6, 8, 6, 8, 6, 8], [4, 6, 4, 6, 4, 6], [8, 6, 8, 6, 8, 6], [6, 4, 6, 4, 6, 4]]}
In out {'input': [[7, 9], [4, 3]], 'output': [[7, 9, 7, 9, 7, 9], [4, 3, 4, 3, 4, 3], [9, 7, 9, 7, 9, 7], [3, 4, 3, 4, 3, 4], [7, 9, 7, 9, 7, 9], [4, 3, 4, 3, 4, 3]]}
In out {'input': [[3, 2], [7, 8]], 'output': [[3, 2, 3, 2, 3, 2], [7, 8, 7, 8, 7, 8], [2, 3, 2, 3, 2, 3], [8, 7, 8, 7, 8, 7], [3, 2, 3, 2, 3, 2], [7, 8, 7, 8, 7, 8]]}


In [17]:
import numpy as np
"""
Rotate a matrix (square or rectangle) clockwise
with two tests
"""
def rotate_clockwise(matrix):
    return np.array(list(zip(*(reversed(matrix)))))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_clockwise(matrix_square))
print(rotate_clockwise(matrix_rectangle))

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
None
[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
[[5 1]
 [6 2]
 [7 3]
 [8 4]]


In [7]:
import numpy as np
"""
Rotate a matrix (square or rectangle) anticlockwise
with two tests
"""
def rotate_anticlockwise(matrix):
    return np.array(list(zip(*matrix))[::-1])

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_anticlockwise(matrix_square))
print(rotate_anticlockwise(matrix_rectangle))

[[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
[[4 8]
 [3 7]
 [2 6]
 [1 5]]


In [9]:
import numpy as np
"""
reverse a matrix (square or rectangle)
with two tests
"""
def reverse(matrix):
    return np.array(list(reversed(matrix)))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(reverse(matrix_square))
print(reverse(matrix_rectangle))

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[5 6 7 8]
 [1 2 3 4]]


In [ ]:
import numpy as np

def add_border(matrix):
    return np.pad(matrix,1,mode='constant',constant_values=10)

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]

m1 = add_border(matrix_square)
m2 = add_border(matrix_rectangle)
print(m1)
print(m2)

[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10  9 10 11 12 10]
 [10 13 14 15 16 10]
 [10 10 10 10 10 10]]
[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10 10 10 10 10 10]]


In [13]:
import numpy as np

def matrix_per_color(matrix):
    """
    Extract all equal color pixels from a matrix and return one matrix per color
    :param matrix:
    :return: result_matrices
    """
    result_matrices = []
    for i in np.unique(matrix):
        matrix_check_for_i = np.copy(matrix == i)
        result_matrix = matrix * matrix_check_for_i
        result_matrices.append(result_matrix)
    return result_matrices

matrix_one = [[1, 2, 1], [2, 2, 2], [3, 1, 1]]
matrix_two = [[1, 5, 2], [5, 2, 1], [2, 1, 6]]

results_one = matrix_per_color(matrix_one)
results_two = matrix_per_color(matrix_two)

print(results_one)
print()
print(results_two)

[array([[1, 0, 1],
       [0, 0, 0],
       [0, 1, 1]]), array([[0, 2, 0],
       [2, 2, 2],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 0, 0],
       [3, 0, 0]])]

[array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]]), array([[0, 0, 2],
       [0, 2, 0],
       [2, 0, 0]]), array([[0, 5, 0],
       [5, 0, 0],
       [0, 0, 0]]), array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 6]])]
