# ARC CHALLENGE PLAYGROUND AND TESTING AREA

In [45]:
import os
import json
import numpy as np

TRAINING_DATA_FOLDER_NAME = 'arcdata/evaluation';
fileNames = os.listdir(TRAINING_DATA_FOLDER_NAME);

def evaluate_effectiveness_of_function():
    with open(f'{TRAINING_DATA_FOLDER_NAME}/{fileNames[0]}', 'r') as file:
        data = json.loads(file.read())
        for i in data['train']:
            print('In out', i)
        for i in data['test']:
            print('In out', i)
evaluate_effectiveness_of_function()


In out {'input': [[8, 6], [6, 4]], 'output': [[8, 6, 8, 6, 8, 6], [6, 4, 6, 4, 6, 4], [6, 8, 6, 8, 6, 8], [4, 6, 4, 6, 4, 6], [8, 6, 8, 6, 8, 6], [6, 4, 6, 4, 6, 4]]}
In out {'input': [[7, 9], [4, 3]], 'output': [[7, 9, 7, 9, 7, 9], [4, 3, 4, 3, 4, 3], [9, 7, 9, 7, 9, 7], [3, 4, 3, 4, 3, 4], [7, 9, 7, 9, 7, 9], [4, 3, 4, 3, 4, 3]]}
In out {'input': [[3, 2], [7, 8]], 'output': [[3, 2, 3, 2, 3, 2], [7, 8, 7, 8, 7, 8], [2, 3, 2, 3, 2, 3], [8, 7, 8, 7, 8, 7], [3, 2, 3, 2, 3, 2], [7, 8, 7, 8, 7, 8]]}


In [17]:
import numpy as np
"""
Rotate a matrix (square or rectangle) clockwise
with two tests
"""
def rotate_clockwise(matrix):
    return np.array(list(zip(*(reversed(matrix)))))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_clockwise(matrix_square))
print(rotate_clockwise(matrix_rectangle))

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
None
[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
[[5 1]
 [6 2]
 [7 3]
 [8 4]]


In [7]:
import numpy as np
"""
Rotate a matrix (square or rectangle) anticlockwise
with two tests
"""
def rotate_anticlockwise(matrix):
    return np.array(list(zip(*matrix))[::-1])

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_anticlockwise(matrix_square))
print(rotate_anticlockwise(matrix_rectangle))

[[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
[[4 8]
 [3 7]
 [2 6]
 [1 5]]


In [9]:
import numpy as np
"""
reverse a matrix (square or rectangle)
with two tests
"""
def reverse(matrix):
    return np.array(list(reversed(matrix)))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(reverse(matrix_square))
print(reverse(matrix_rectangle))

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[5 6 7 8]
 [1 2 3 4]]


In [ ]:
import numpy as np

def add_border(matrix):
    return np.pad(matrix,1,mode='constant',constant_values=10)

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]

m1 = add_border(matrix_square)
m2 = add_border(matrix_rectangle)
print(m1)
print(m2)

[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10  9 10 11 12 10]
 [10 13 14 15 16 10]
 [10 10 10 10 10 10]]
[[10 10 10 10 10 10]
 [10  1  2  3  4 10]
 [10  5  6  7  8 10]
 [10 10 10 10 10 10]]


In [2]:
import numpy as np

def equal_matrix_dimensions(matrix_one, matrix_two):
    """
    Checks if dimensions of input matrix and output matrix are equal
    :param array_one:
    :param array_two:
    :return: boolean
    """

    matrix_one_new = np.asarray(matrix_one)
    matrix_two_new = np.asarray(matrix_two)
    return matrix_one_new.shape == matrix_two_new.shape

matrix_one = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_two = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
matrix_three = [[1,2,3,4],[5,6,7,8]]

print(equal_matrix_dimensions(matrix_one, matrix_two))
print(equal_matrix_dimensions(matrix_one, matrix_three))

True
False


In [1]:
import numpy as np

def get_pixel_neighbours(matrix, pixel):
    neighbours = np.zeros((3,3))
    for i in range(3):
        for j in range(3):
            neighbours[i, j] = matrix[pixel[0]-1+i, pixel[1]-1+j]
    return neighbours

matrix_square = np.array([[1,2,3,4],
                          [5,6,7,8],
                          [9,10,11,12],
                          [13,14,15,16]])
matrix_rectangle = np.array([[1,2,3,4],
                             [5,6,7,8]])

print(get_pixel_neighbours(matrix_square,[0,1]))
print(get_pixel_neighbours(matrix_square,[2,1]))
print(get_pixel_neighbours(matrix_rectangle,[0,1]))

[[13. 14. 15.]
 [ 1.  2.  3.]
 [ 5.  6.  7.]]
[[ 5.  6.  7.]
 [ 9. 10. 11.]
 [13. 14. 15.]]
[[5. 6. 7.]
 [1. 2. 3.]
 [5. 6. 7.]]


In [1]:
import numpy as np


def gravitate_pixel(matrix, pixel):
    """
    Pixel following the gravitational force to the lowest possible field in the matrix
    :param matrix:
    :param pixel: which should be moved
    :return: matrix_changed
    """

    point = (pixel[1], pixel[0])
    row = point[0]
    column = point[1]
    matrix_changed = np.asarray(matrix)
    print("before: \n", matrix_changed)
    color = matrix_changed[row][column]
    matrix_changed[row][column] = 0
    shape = matrix_changed.shape[0]
    for i in range(row+1, shape):
        if matrix[i][column] == 0:
            continue
        if matrix[i][column] != 0:
            point_new = (i-1, column)
            matrix_changed[point_new[0]][point_new[1]] = color
        else:
            point_new = (i, column)
            matrix_changed[point_new[0]][point_new[1]] = color
    return matrix_changed #add matrix.tolist() when convert to input type of matrix


matrix = [[0,0,2,0],[0,2,0,0],[0,0,0,0],[1,1,1,1]]

pixel = [2, 0]

print("after: \n", gravitate_pixel(matrix,pixel))


before: 
 [[0 0 2 0]
 [0 2 0 0]
 [0 0 0 0]
 [1 1 1 1]]
after: 
 [[0 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [1 1 1 1]]
