# ARC CHALLENGE PLAYGROUND AND TESTING AREA

In [80]:
import os
import json
import numpy as np
"""
The idea of this function is that a newly created library function can be tested directly on the evaluation data 
(how many problems could be solved right away with this functionality).
"""
TRAINING_DATA_FOLDER_NAME = 'arcdata/evaluation';
fileNames = os.listdir(TRAINING_DATA_FOLDER_NAME);
fileNames = list(filter(lambda x: 'label' not in x, fileNames))

def evaluate_effectiveness_of_function(function):
    solved_files = []
    #print(fileNames)
    for fileName in fileNames:
        with open(f'{TRAINING_DATA_FOLDER_NAME}/{fileName}', 'r') as file:
            data = json.loads(file.read())
            result = []
            #print(data)
            for i in data['train']:
                #print(i)
                result.append(np.array_equal(function(i['input']), np.array(i['output'])))
            if np.all(result):
                solved_files.append(fileName)
    return solved_files

In [81]:
import numpy as np
"""
Rotate a matrix (square or rectangle) clockwise
with two tests
"""
def rotate_clockwise(matrix):
    return np.array(list(zip(*(reversed(matrix)))))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_clockwise(matrix_square))
print(rotate_clockwise(matrix_rectangle))
print(evaluate_effectiveness_of_function(rotate_clockwise))

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
[[5 1]
 [6 2]
 [7 3]
 [8 4]]
[]


In [82]:
import numpy as np
"""
Rotate a matrix (square or rectangle) anticlockwise
with two tests
"""
def rotate_anticlockwise(matrix):
    return np.array(list(zip(*matrix))[::-1])

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(rotate_anticlockwise(matrix_square))
print(rotate_anticlockwise(matrix_rectangle))
print(evaluate_effectiveness_of_function(rotate_anticlockwise))

[[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
[[4 8]
 [3 7]
 [2 6]
 [1 5]]
[]


In [83]:
import numpy as np
"""
reverse a matrix (square or rectangle)
with two tests
"""
def reverse(matrix):
    return np.array(list(reversed(matrix)))

matrix_square = [[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]]
matrix_rectangle = [[1,2,3,4],
                    [5,6,7,8]]
print(reverse(matrix_square))
print(reverse(matrix_rectangle))
print(evaluate_effectiveness_of_function(reverse))

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[5 6 7 8]
 [1 2 3 4]]
[]
